---
title: Stative verb ‘remain’, negative present tense
author: Nastya Ivanova
date: 'Last update: `r lubridate::make_datetime(year = 2023, month = 12, day = 13)`'
output:
  html_document:
    number_sections: true
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE, fig.width = 9.5)
library(tidyverse)
library(lingtypology)
read_csv('data/database.csv', show_col_types = FALSE) |> 
  filter(feature_id == 164) ->
  db
read_csv('data/villages.csv') |> 
  filter(!(village %in% c('Kazankulak', 'Novyy Borch', 'Vrush', 'Aran', 'Khnyukh'))) ->
  villages
  
villages |> 
  filter(!(village %in% c('Tsudik', 'Borch'))) ->
  villages4map
  
```

In the negative present tense, the stative verbs employ the suffix which is identical to the negative present-tense copula. It is -diš in the majority of varieties (e.g. mar-diš ‘does not remain there’), and -ǯiš in Shinaz.


## Gender 1

::: {.panel-tabset}

### Map

```{r}
db |> 
  filter(feature_lexeme == 'Gender 1')  |>
  filter(!is.na(value),
         value != 'NO DATA') |>
  mutate(value = str_split(value, ' ; ')) |> 
  unnest_longer(value) |> 
  distinct(settlement, value) |> 
  mutate(n = 1) |> 
  pivot_wider(names_from = value, values_from = n, values_fill = 0) |> 
  left_join(villages[,c('village', 'lat', 'lon')], c('settlement' = 'village')) |> 
  mutate(language = 'Rutul') ->
  for_map
  
if(length(for_map) == 5){
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
              latitude = for_map$lat,
              longitude = for_map$lon,
              label = for_map$settlement,
              label.position = 'top',
              label.hide = FALSE,
              width = 10,
              tile = 'OpenStreetMap.HOT',
              features = colnames(for_map)[2],
              pipe.data = _)  
} else {
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
            latitude = for_map$lat,
            longitude = for_map$lon,
            minichart.data = for_map |> select(-settlement, -lat, -lon, -language),
            minichart = 'pie', 
            width = 3,
            tile = 'OpenStreetMap.HOT',
            pipe.data = _)
}
```

### Data

```{r}
db |> 
  filter(feature_lexeme == 'Gender 1') |> 
  select(settlement, value, stimuli, answer, collected) |> 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```
:::

## Gender 2

::: {.panel-tabset}

### Map

```{r}
db |> 
  filter(feature_lexeme == 'Gender 2')  |>
  filter(!is.na(value),
         value != 'NO DATA') |>
  mutate(value = str_split(value, ' ; ')) |> 
  unnest_longer(value) |> 
  distinct(settlement, value) |> 
  mutate(n = 1) |> 
  pivot_wider(names_from = value, values_from = n, values_fill = 0) |> 
  left_join(villages[,c('village', 'lat', 'lon')], c('settlement' = 'village')) |> 
  mutate(language = 'Rutul') ->
  for_map
  
if(length(for_map) == 5){
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
              latitude = for_map$lat,
              longitude = for_map$lon,
              label = for_map$settlement,
              label.position = 'top',
              label.hide = FALSE,
              width = 10,
              tile = 'OpenStreetMap.HOT',
              features = colnames(for_map)[2],
              pipe.data = _)  
} else {
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
            latitude = for_map$lat,
            longitude = for_map$lon,
            minichart.data = for_map |> select(-settlement, -lat, -lon, -language),
            minichart = 'pie', 
            width = 3,
            tile = 'OpenStreetMap.HOT',
            pipe.data = _)
}
```

### Data

```{r}
db |> 
  filter(feature_lexeme == 'Gender 2') |> 
  select(settlement, value, stimuli, answer, collected) |> 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```
:::

## Gender 3

::: {.panel-tabset}

### Map

```{r}
db |> 
  filter(feature_lexeme == 'Gender 3')  |>
  filter(!is.na(value),
         value != 'NO DATA') |>
  mutate(value = str_split(value, ' ; ')) |> 
  unnest_longer(value) |> 
  distinct(settlement, value) |> 
  mutate(n = 1) |> 
  pivot_wider(names_from = value, values_from = n, values_fill = 0) |> 
  left_join(villages[,c('village', 'lat', 'lon')], c('settlement' = 'village')) |> 
  mutate(language = 'Rutul') ->
  for_map
  
if(length(for_map) == 5){
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
              latitude = for_map$lat,
              longitude = for_map$lon,
              label = for_map$settlement,
              label.position = 'top',
              label.hide = FALSE,
              width = 10,
              tile = 'OpenStreetMap.HOT',
              features = colnames(for_map)[2],
              pipe.data = _)  
} else {
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
            latitude = for_map$lat,
            longitude = for_map$lon,
            minichart.data = for_map |> select(-settlement, -lat, -lon, -language),
            minichart = 'pie', 
            width = 3,
            tile = 'OpenStreetMap.HOT',
            pipe.data = _)
}
```

### Data

```{r}
db |> 
  filter(feature_lexeme == 'Gender 3') |> 
  select(settlement, value, stimuli, answer, collected) |> 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```
:::

## Gender 4

::: {.panel-tabset}

### Map

```{r}
db |> 
  filter(feature_lexeme == 'Gender 4')  |>
  filter(!is.na(value),
         value != 'NO DATA') |>
  mutate(value = str_split(value, ' ; ')) |> 
  unnest_longer(value) |> 
  distinct(settlement, value) |> 
  mutate(n = 1) |> 
  pivot_wider(names_from = value, values_from = n, values_fill = 0) |> 
  left_join(villages[,c('village', 'lat', 'lon')], c('settlement' = 'village')) |> 
  mutate(language = 'Rutul') ->
  for_map
  
if(length(for_map) == 5){
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
              latitude = for_map$lat,
              longitude = for_map$lon,
              label = for_map$settlement,
              label.position = 'top',
              label.hide = FALSE,
              width = 10,
              tile = 'OpenStreetMap.HOT',
              features = colnames(for_map)[2],
              pipe.data = _)  
} else {
map.feature(languages = 'Rutul',
            latitude = villages4map$lat,
            longitude = villages4map$lon,
            label = villages4map$village,
            label.position = 'top',
            label.hide = FALSE,
            width = 10,
            color = 'gray',
            tile = 'OpenStreetMap.HOT',
            opacity = 0.4) |> 
  map.feature(languages = for_map$language,
            latitude = for_map$lat,
            longitude = for_map$lon,
            minichart.data = for_map |> select(-settlement, -lat, -lon, -language),
            minichart = 'pie', 
            width = 3,
            tile = 'OpenStreetMap.HOT',
            pipe.data = _)
}
```

### Data

```{r}
db |> 
  filter(feature_lexeme == 'Gender 4') |> 
  select(settlement, value, stimuli, answer, collected) |> 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```
:::

