---
title: 2pl pronoun
author: George Moroz
date: 'Last update: `r lubridate::make_datetime(year = 2022, month = 6, day = 18)`'
bibliography: ./data/bibliography.bib
link-citations: true
output:
  html_document:
    number_sections: true
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = '')
```

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE, fig.width = 9.5)
library(tidyverse)
library(lingtypology)
db <- read_csv('data/database.csv')  %>% filter(feature_id == 2)

villages <- read_csv('data/villages.csv')
db %>% 
  distinct(settlement, value) %>% 
  mutate(n = 1) %>% 
  pivot_wider(names_from = value, values_from = n, values_fill = 0) %>% 
  left_join(villages[,c('village', 'lat', 'lon')], c('settlement' = 'village')) %>% 
  mutate(language = 'Rutul') ->
  for_map
```

Form of 2pl pronoun


## Map

```{r}
map.feature(languages = for_map$language,
            latitude = for_map$lat,
            longitude = for_map$lon,
            label = for_map$settlement,
            label.position = 'top',
            label.hide = FALSE,
            minichart.data = for_map %>% select(-settlement, -lat, -lon, -language),
            minichart = 'pie', 
            width = 3)
```

## Data

```{r}
db %>% 
  select(collected, settlement, value, stimuli, raw_data) %>% 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```

## Reference

